MatConst.E1 = E1;
MatConst.E2 = E2;
MatConst.v12 = v12;
MatConst.v21 = (MatConst.E2*MatConst.v12)/MatConst.E1;
MatConst.G12 = G12;
MatConst.NumPlies = NumPlies;
MatConst.fx = fx;
MatConst.fy = fy;
MatConst.fxy = fxy;
MatConst.Nx = Nx;
MatConst.Ny = Ny;
MatConst.Nxy = Nxy;
MatConst.Mx = Mx;
MatConst.My = My;
MatConst.Mxy = Mxy;

            MatConst.E1 = 
            MatConst.E2 = 
            MatConst.v12 =
            
            MatConst.G12 = 
            MatConst.NumPlies = 
            MatConst.fx = 
            MatConst.fy = 
            MatConst.fxy = 
            MatConst.Nx = 
            MatConst.Ny = 
            MatConst.NXy = 
            MatConst.Mx = 
            MatConst.My = 
            MatConst.Mxy =